import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/catppuccin-latte.toml",
  # "~/.config/alacritty/themes/catppuccin-frappe.toml",
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml",
  "~/.config/alacritty/themes/catppuccin-mocha.toml",
  "~/.config/alacritty/keybindings.toml",
]


live_config_reload = true

[env]
ZELLIJ_AUTO_ATTACH = "true"

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
shape = "Beam"

[font]
size = 12

[font.bold]
family = "Fira Code"


[font.bold_italic]
family = "Fira Code"


[font.italic]
family = "Fira Code"


[font.normal]
family = "Fira Code"
style = "Regular"

# Alacritty 为默认终端，[shell]可注释
# echo 'eval "$(zellij setup --generate-auto-start zsh)"' >> ~/.zshrc
# [shell]
# args = ["attach", "--index=0", "--create"]
# program = "zellij"

# [font.glyph_offset]
# x = 0
# y = 1
#
# [font.offset]
# x = 0
# y = 1

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Transparent"
blur = true
opacity = 0.9

[window.dimensions]
columns = 80
lines = 30

[window.padding]
x = 10
y = 22
