
[[keyboard.bindings]]
chars = "\f"
key = "R"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ClearHistory"
key = "R"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "Hide"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"

# [[keyboard.bindings]]
# action = "SpawnNewInstance"
# key = "N"
# mods = "Control"
#
# [[keyboard.bindings]]
# action = "CreateNewWindow"
# key = "T"
# mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"
